title: der flo
email: "mail [at] derflo [dot] io"
description: >- # this means to ignore newlines until "baseurl:"
  Gewidmet meinen wundervollen Töchtern.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: flowinho
github_username:  flowinho
permalink: :year/:month/:day/:title:output_ext

# Minima settings
header_pages:
  - blog.md
  - ueber-den-papa.md
  - ueber-den-entwickler.md
  - portfolio.md
  - ueber-den-fotograf.md
  - ueber-den-podcaster.md
  - ueber-diese-seite.md
  - downloads.md
  - kontakt.md


# Build settings


highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

future: false
timezone: Europe/Berlin
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
